name: publish to DO

on: [workflow_dispatch]

jobs:
  publish:
    name: 'Build and publish image'
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      IMAGE_TAG_PREFIX: ${{ secrets.IMAGE_TAG_PREFIX }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_API_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_API_KEY }}
      NEXT_PUBLIC_SUPABASE_BUCKET: ${{ secrets.NEXT_PUBLIC_SUPABASE_BUCKET }}
      NEXT_PUBLIC_SUPABASE_DOCUMENTS_TABLE: ${{ secrets.NEXT_PUBLIC_SUPABASE_DOCUMENTS_TABLE }}
      NEXT_PUBLIC_SUPABASE_CHAT_RECORDS_TABLE: ${{ secrets.NEXT_PUBLIC_SUPABASE_CHAT_RECORDS_TABLE }}
      NEXT_PUBLIC_SUPABASE_DOCUMENT_CHUNKS_TABLE: ${{ secrets.NEXT_PUBLIC_SUPABASE_DOCUMENT_CHUNKS_TABLE }}
      NEXT_PUBLIC_ORIGIN: ${{ secrets.NEXT_PUBLIC_ORIGIN }}
      NEXT_PUBLIC_OPENAI_API_KEY: ${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -t ${{ env.IMAGE_TAG_PREFIX }}:latest \
            --build-arg NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
            --build-arg NEXT_PUBLIC_SUPABASE_API_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_API_KEY }} \
            --build-arg NEXT_PUBLIC_SUPABASE_BUCKET=${{ secrets.NEXT_PUBLIC_SUPABASE_BUCKET }} \
            --build-arg NEXT_PUBLIC_SUPABASE_DOCUMENTS_TABLE=${{ secrets.NEXT_PUBLIC_SUPABASE_DOCUMENTS_TABLE }} \
            --build-arg NEXT_PUBLIC_SUPABASE_CHAT_RECORDS_TABLE=${{ secrets.NEXT_PUBLIC_SUPABASE_CHAT_RECORDS_TABLE }} \
            --build-arg NEXT_PUBLIC_SUPABASE_DOCUMENT_CHUNKS_TABLE=${{ secrets.NEXT_PUBLIC_SUPABASE_DOCUMENT_CHUNKS_TABLE }} \
            --build-arg NEXT_PUBLIC_ORIGIN=${{ secrets.NEXT_PUBLIC_ORIGIN }} \
            --build-arg NEXT_PUBLIC_OPENAI_API_KEY=${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }} \
            .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Push image
        run: |
          doctl registry login
          docker push ${{ env.IMAGE_TAG_PREFIX }}:latest
