name: publish to DO

on: [workflow_dispatch]

jobs:
  publish:
    name: 'Build and publish image'
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      IMAGE_TAG_PREFIX: ${{ secrets.IMAGE_TAG_PREFIX }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t ${{ env.IMAGE_TAG_PREFIX }}:latest .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Push image
        run: |
          docker push ${{ env.IMAGE_TAG_PREFIX }}:latest
